import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/Header'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/components/Footer/Footer';
import HeroBanner from '@/components/HeroBanner/HeroBanner';
import Services from '@/components/Services/Services';
import '@fortawesome/fontawesome-free/css/all.min.css';
import Resume from '@/components/Resume/Resume';
import About from '@/components/About/About';
import Portfolio from '@/components/Portfolio/Portfolio';
import Contact from '@/components/Contact/Contact';
import Faq from '@/components/Faq/Faq';
import React,{useEffect} from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';





const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    AOS.init();
  }, [])
  return (
    <>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Header />
       <HeroBanner />
       <About />
       <Services />
       <Resume />
      <Portfolio />
      <Faq />
       <Contact />
       <Footer />
      </main>
    </>
  )
}
